easy_admin:
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    entities:
        Utilisateurs:
            class:  App\Entity\User
            label: 'Utilisateurs'
            list: 
                fields:
                    - 'id'
                    - { property: 'email', type: 'email' }
                    - 'firstName'
                    - 'lastName'
                    - 'roles'
            show: 
                fields:
                    - 'id'
                    - { property: 'email', type: 'email' }
                    - 'firstName'
                    - 'lastName'
                    - 'roles'
            form: 
                fields:
                    - { property: 'email', type: 'email' }
                    - { property: 'roles', type: 'collection' }
                    - 'firstName'
                    - 'lastName'
        Questionnaires:
            class: App\Entity\Questionnaire
            list:
                fields:
                    - 'id'
                    - 'name'
                    - 'slug'
                    - 'leader.email'
                    - { property: 'logoName', type: 'image', base_path: '/img/questionnaire' }
            show: 
                fields:
                    - 'name'
                    - 'slug'
                    - 'summary'
                    - 'leader.email'
            form:
                fields:
                    - { property: 'name', label: 'Titre' }
                    - { property: 'slug', label: "Lien d'accès", help: "Saisir 'monlien' pour activer l'url" }
                    - { property: 'leader', label: 'Animateur', type_options: { choice_label: 'email' } }      
                    - { property: 'summary', type: 'fos_ckeditor', label: 'Description'}                
                    - { property: 'isOpen', label: 'Accessible'}    
                    - { property: 'topics', label: 'Thèmes'}    
                    - { property: 'profiles', label: 'Profils manager'}    
                    - { property: 'logoFile', type: 'vich_image' }
        Themes:
            class: App\Entity\Topic
        Profils:
            class: App\Entity\Profile
            list:
                fields:
                    - 'id'
                    - 'title'
                    - 'content'
                    - 'questionnaire'
                    - 'statements'
            show: 
                fields:
                    - 'title'
                    - 'content'
                    - 'questionnaire'
                    - 'statements'
            form:
                fields:
                    - 'title'
                    - { property: 'content', type: 'fos_ckeditor'}
                    - 'questionnaire'
                    - 'statements'
        Affirmations:
            class: App\Entity\Statement
            list:
                fields:
                    - 'id'
                    - 'title'
                    - 'topic'
                    - 'records'
                    - 'profile'
            show: 
                fields:
                    - 'title'
                    - 'topic'
                    - 'records'
                    - 'profile'
            form:
                fields:
                    - 'title'
                    - 'topic'
                    - 'profile'
        Enregistrements: 
            class: App\Entity\Record
        Tracks: 
            class: App\Entity\Track