vich_uploader:
    db_driver: orm

    mappings:
        course_logo:
            uri_prefix: /img/course
            upload_destination: '%kernel.project_dir%/public/img/course'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
