vich_uploader:
    db_driver: orm

    mappings:
        questionnaire_logo:
            uri_prefix: /img/questionnaire
            upload_destination: '%kernel.project_dir%/public/img/questionnaire'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
